# Generated by Django 4.2.7 on 2026-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='widget_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Widget display settings (background, size, etc.)'),
        ),
    ]
