# Generated by Django 5.2.11 on 2026-02-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_widget_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, help_text='City or location of the item', max_length=100, null=True),
        ),
    ]
