# Generated by Django 4.2.7 on 2026-02-24

from django.db import migrations, models


def set_initial_display_order(apps, schema_editor):
    Category = apps.get_model("auctions", "Category")
    for index, category in enumerate(Category.objects.order_by("name"), start=1):
        Category.objects.filter(pk=category.pk).update(display_order=index)


def reset_display_order(apps, schema_editor):
    Category = apps.get_model("auctions", "Category")
    Category.objects.all().update(display_order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_add_category_icon_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_initial_display_order, reset_display_order),
    ]
