# Generated by Django 5.2.11 on 2026-02-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
