# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhistory',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidhistory',
            name='previous_highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_history_as_previous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auto_bid_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='bidding.autobidrule'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autobidrule',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bid_rules', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='autobidrule',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bid_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'created_at'], name='bidding_bid_auction_d1ea3d_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'created_at'], name='bidding_bid_bidder__12624c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='autobidrule',
            unique_together={('auction', 'bidder')},
        ),
    ]
