# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'db_table': 'vehicles_fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
                'db_table': 'vehicles_transmission',
            },
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('value_multiplier', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Vehicle Condition',
                'verbose_name_plural': 'Vehicle Conditions',
                'db_table': 'vehicles_condition',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'db_table': 'vehicles_type',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine_displacement', models.IntegerField(blank=True, help_text='in CC', null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField(blank=True, help_text='L/100km', null=True)),
                ('mileage', models.IntegerField(help_text='in kilometers')),
                ('service_history', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text="List of features: ['ABS', 'Airbags', 'Air Conditioning', 'Power Windows', 'Power Steering', etc.]")),
                ('ownership_documents', models.BooleanField(default=True)),
                ('accident_history', models.TextField(blank=True, help_text='Details of any accidents')),
                ('insurance_valid', models.BooleanField(default=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='inspections/')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='auctions.auction')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehiclecondition')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.fueltype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.transmission')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles_vehicle',
                'indexes': [models.Index(fields=['vin'], name='vehicles_ve_vin_d8dea1_idx'), models.Index(fields=['make', 'model'], name='vehicles_ve_make_6615f9_idx'), models.Index(fields=['year'], name='vehicles_ve_year_656e54_idx'), models.Index(fields=['created_at'], name='vehicles_ve_created_3aff09_idx')],
            },
        ),
    ]
