# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionvideo',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionvideo',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['auction', 'document_type'], name='media_docum_auction_7c8729_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', 'document_type'], name='media_docum_user_id_186081_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionimage',
            index=models.Index(fields=['auction', 'is_primary'], name='media_aucti_auction_0c1785_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionimage',
            index=models.Index(fields=['created_at'], name='media_aucti_created_d01185_idx'),
        ),
    ]
