# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('multi_account', 'Multiple accounts'), ('velocity', 'High velocity activity'), ('pattern', 'Suspicious pattern'), ('payment_mismatch', 'Payment mismatch'), ('geographic_anomaly', 'Geographic anomaly'), ('device_fingerprint', 'Device fingerprint mismatch')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_signal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiAccountDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_method', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_multi_account_detection',
            },
        ),
        migrations.CreateModel(
            name='VelocityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bid', 'Bid'), ('login', 'Login'), ('payment', 'Payment'), ('account_creation', 'Account creation')], max_length=50)),
                ('action_count', models.IntegerField()),
                ('time_window_seconds', models.IntegerField(default=3600)),
                ('threshold_exceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_velocity_check',
                'ordering': ['-created_at'],
            },
        ),
    ]
