# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='velocitycheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiaccountdetection',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiaccountdetection',
            name='primary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_account_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudsignal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudsignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='multiaccountdetection',
            unique_together={('primary_user', 'linked_user')},
        ),
        migrations.AddIndex(
            model_name='fraudsignal',
            index=models.Index(fields=['user', 'risk_level'], name='fraud_signa_user_id_f25ded_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudsignal',
            index=models.Index(fields=['is_reviewed', 'risk_level'], name='fraud_signa_is_revi_7a9106_idx'),
        ),
    ]
