# Generated by Django 4.2.7 on 2026-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_ban', 'User ban'), ('user_unban', 'User unban'), ('auction_cancel', 'Auction cancellation'), ('settings_change', 'Settings change'), ('fraud_review', 'Fraud review'), ('payment_refund', 'Payment refund')], max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adminpanel_admin_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fraud', 'Fraud'), ('counterfeit', 'Counterfeit item'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adminpanel_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_snipe_default_seconds', models.IntegerField(default=30)),
                ('min_reserve_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_auction_duration_days', models.IntegerField(default=30)),
                ('kyc_enabled', models.BooleanField(default=False)),
                ('seller_verification_enabled', models.BooleanField(default=False)),
                ('deposit_system_enabled', models.BooleanField(default=False)),
                ('fraud_detection_enabled', models.BooleanField(default=True)),
                ('auto_ban_on_fraud', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'adminpanel_system_settings',
            },
        ),
    ]
