# Generated by Django 5.2.11 on 2026-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for the website', null=True, upload_to='favicons/'),
        ),
    ]
